// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace AvServiceHR.Models
{
    public partial class uspGetWhereUsedProductIDResult
    {
        public int? ProductAssemblyID { get; set; }
        public int? ComponentID { get; set; }
        public string ComponentDesc { get; set; }
        public decimal? TotalQuantity { get; set; }
        public decimal? StandardCost { get; set; }
        public decimal? ListPrice { get; set; }
        public short? BOMLevel { get; set; }
        public int? RecursionLevel { get; set; }
    }
}
